### PR TITLE
Hopefully fixed all rubocop issues, slightly updated documentation headers

### PR DESCRIPTION
**Pull request by loualrid**

### CODE REVIEW

**Comment by mattyjones** [comment]
@loualrid Everything looks good, the only request is if you could please add descriptions for all the options ;)  It will make everyone's life easier in the future.  When that is done I will merge and bump.

Thanks!

**Comment by loualrid** [comment]
In case you were waiting for a comment, what you requested was done 3 days ago with the last commit. That is, unless the changes were unsatisfactory.

**Comment by mattyjones** [comment]
@loualrid  I must of missed it, Thanks!

**Comment by loualrid** [comment]
@mattyjones After digging more into $CHILD_STATUS , it may not work for the majority of use cases (it doesn't work for mine). If this is brought up in the future, it'll have to be changed back to $? to check the exitstatus of the rspec process. The problem is that travis will complain about $?

**Comment by mattyjones** [comment]
@loualrid I remember something about this and using the English pkg but can't recall off the top of my head.

**Pull request merged**
